# /// script
# requires-python = ">=3.10"
# dependencies = ["PyYAML"]
# ///
"""Generate the agent configs used in the DRPG paper.

Every config in ``configs/agent/`` is produced by this script, so the whole
method x model grid stays consistent: change a shared hyper-parameter here and
regenerate instead of editing 35 YAML files by hand.

Usage:
    uv run scripts/gen_configs.py                # regenerate configs/agent/
    uv run scripts/gen_configs.py --out /tmp/cfg # write somewhere else
    uv run scripts/gen_configs.py --check        # fail if the tree is stale

To evaluate a model that is not in the paper, add an entry to ``MODELS`` (the
``series`` field selects a backend in ``stream_bench/llms/``) and rerun.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import yaml

# Shared experimental setup (Section 4.5 of the paper).
TEMPERATURE = 0.0
MAX_TOKENS = 1024
SEED = 42
EMBEDDING_MODEL = "BAAI/bge-base-en-v1.5"
# top_k = 16 here; run_bench.py lowers it to 4 for DS-1000 and HotpotQA so that
# the few-shot block fits in the context window.
TOP_K = 16

# slug -> (series, model_name). The seven models of Table 1.
MODELS: dict[str, tuple[str, str]] = {
    "gemini-2.0-flash": ("gemini_dev", "gemini-2.0-flash"),
    "gemini-2.0-flash-lite": ("gemini_dev", "gemini-2.0-flash-lite"),
    "llama-3.3-70b": ("nvidia", "meta/llama-3.3-70b-instruct"),
    "llama-4-maverick": ("nvidia", "meta/llama-4-maverick-17b-128e-instruct"),
    "llama-4-scout": ("nvidia", "meta/llama-4-scout-17b-16e-instruct"),
    "mistral-medium": ("nvidia", "mistralai/mistral-medium-3-instruct"),
    "mistral-small": ("nvidia", "mistralai/mistral-small-3.1-24b-instruct-2503"),
}


def llm_block(slug: str) -> dict:
    series, model_name = MODELS[slug]
    return {
        "series": series,
        "model_name": model_name,
        "temperature": TEMPERATURE,
        "max_tokens": MAX_TOKENS,
    }


def rag_block() -> dict:
    return {
        "embedding_model": EMBEDDING_MODEL,
        "top_k": TOP_K,
        "order": "similar_at_bottom",  # most similar example closest to the question
        "rag_filename": None,  # defaults to the run's log path + ".db"
        "seed": SEED,
    }


def zeroshot(slug: str) -> dict:
    return {"agent_name": "zeroshot", "seed": SEED, "llm": llm_block(slug)}


def self_refine(slug: str) -> dict:
    return {"agent_name": "self_refine", "seed": SEED, "llm": llm_block(slug)}


def self_stream_icl(slug: str) -> dict:
    return {
        "agent_name": "self_stream_icl",
        "mode": "only_correct",  # only correct cases are written to memory
        "enabled_cot": False,
        "seed": SEED,
        "llm": llm_block(slug),
        "rag": rag_block(),
    }


def drpg(slug: str, policy_slug: str | None = None) -> dict:
    """DRPG. ``policy_slug`` sets a different policy generator (Appendix D)."""
    return {
        "agent_name": "rag_policy",
        "mode": "normal",
        "seed": SEED,
        "enabled_cot": False,
        "optimization": False,
        "use_correct_fewshots": True,  # agent also sees retrieved correct examples
        "use_previous_policy": False,  # each policy is generated from scratch
        "policy_generator_mode": "both",  # contrastive: correct + incorrect cases
        "policy_generator_fewshots_num": "half_topk",  # k/2 correct + k/2 incorrect
        "prompt_ver": "original",
        "ewma": {"initial_alpha": 0.2, "initial_ewma": 0.5},
        "llm": llm_block(slug),
        "policy_llm": llm_block(policy_slug or slug),
        "rag": rag_block(),
    }


def dynamic_cheatsheet(slug: str) -> dict:
    """DRPG without environment feedback (Appendix F)."""
    return {
        "agent_name": "dynamic_cheatsheet",
        "seed": SEED,
        "enabled_cot": False,
        "use_fewshots": True,
        "use_previous_policy": False,
        "policy_generator_fewshots_num": "half_topk",
        "prompt_ver": "original",
        "llm": llm_block(slug),
        "policy_llm": llm_block(slug),
        "rag": rag_block(),
    }


BUILDERS = {
    "zeroshot": zeroshot,
    "self_refine": self_refine,
    "self_stream_icl": self_stream_icl,
    "drpg": drpg,
    "dynamic_cheatsheet": dynamic_cheatsheet,
}

# Agent x policy-generator pairs of the cross-generator ablation (Appendix D).
# The same-model pairs of that table are the plain DRPG configs above.
CROSS_GENERATOR = [
    ("llama-4-maverick", "llama-4-scout"),
    ("llama-4-maverick", "mistral-small"),
    ("llama-4-scout", "llama-4-maverick"),
    ("mistral-small", "llama-4-maverick"),
]

HEADER = "# Generated by scripts/gen_configs.py -- edit that script, not this file.\n"


def build() -> dict[str, dict]:
    """Return {relative path: config} for the whole grid."""
    tree: dict[str, dict] = {}
    for method, builder in BUILDERS.items():
        for slug in MODELS:
            tree[f"{method}/{slug}.yml"] = builder(slug)
    for agent_slug, policy_slug in CROSS_GENERATOR:
        tree[f"drpg-cross-generator/{agent_slug}__policy-{policy_slug}.yml"] = drpg(
            agent_slug, policy_slug
        )
    return tree


def dump(config: dict) -> str:
    return HEADER + yaml.safe_dump(config, sort_keys=True, default_flow_style=False)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "configs" / "agent",
        help="Output directory (default: configs/agent).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero if the existing tree differs.",
    )
    args = parser.parse_args()

    tree = build()
    if args.check:
        stale = [
            name
            for name, config in tree.items()
            if not (args.out / name).is_file()
            or (args.out / name).read_text() != dump(config)
        ]
        if stale:
            print("stale or missing configs:", *stale, sep="\n  ")
            return 1
        print(f"{len(tree)} configs up to date")
        return 0

    for method in {name.split("/")[0] for name in tree}:
        shutil.rmtree(args.out / method, ignore_errors=True)
    for name, config in tree.items():
        path = args.out / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(dump(config))
    print(f"wrote {len(tree)} configs to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
